const mongoose = require('mongoose');

/*
 * Log Schema definition.
 * This schema stores application logs generated by the Pino logger.
 */
const logSchema = new mongoose.Schema({
    // Log priority level (info, error, etc.).
    level: String,
    // Unix timestamp of the log event.
    time: Number,
    // The actual log message content.
    msg: String,
    // Process ID and Hostname for debugging microservices.
    pid: Number,
    hostname: String
}, {
    // Allowing flexible structure for dynamic log metadata.
    strict: false
});

// Creating the model based on the schema.
// This model will be used to interact with the 'logs' collection in MongoDB.
const Logs = mongoose.model('Logs', logSchema, 'logs');

// Exporting the model for use in other parts of the application.
module.exports = Logs;