const mongoose = require('mongoose');

/*
 * Log Schema definition.
 * This schema stores application logs generated by the Pino logger.
 */
const logSchema = new mongoose.Schema({
    // Log priority level (info, error, etc.).
    level: String,
    // Unix timestamp of the log event.
    time: Number,
    // The actual log message content.
    msg: String,
    // Process ID and Hostname for debugging microservices.
    pid: Number,
    hostname: String
}, {
    // Allowing flexible structure for dynamic log metadata.
    strict: false
});

// Exporting the model and explicitly naming the collection 'logs'.
module.exports = mongoose.model('Log', logSchema, 'logs');